[build]
  command = "npm run build"
  publish = "_site"


[dev]
  command = "npm run start"


[context.production.environment]
  ELEVENTY_ENV = "production"


[context.deploy-preview.environment]
  MODE = "testing"
